version: '3.8'

services:
  dotnet-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dotnet-chatroom
    env_file:
      - .env.production
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "11115:8080"
    networks:
      - chat_service_network
      - sqlserver-network

networks:
  chat_service_network:
    external: true
  sqlserver-network:
    external: true
