version: '3.8'

services:
  dotnet-app:
    image: dotnet-chatroom:latest
    build: .
    container_name: dotnet-chatroom
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "11115:8080"
    restart: always
    networks:
      - rbmq-network
      - chat_service_network
      - sqlserver-network

networks:
  rbmq-network:
    external: true
  chat_service_network:
    external: true
  sqlserver-network:
    external: true
